#!/usr/bin/env bash

export APP_FOLDER='/usr/src/myapp'
docker run -it --rm --name calculator-api-server -v "$PWD":${APP_FOLDER} -w ${APP_FOLDER} -p 9191:9191 php:7.3-cli-alpine php -S 0.0.0.0:9191 public/index.php
